export const TABS_ADD_ITEM = 'TABS_ADD_ITEM'
export const TABS_REMOVE_ITEM = 'TABS_REMOVE_ITEM'
export const TABS_SELECT_ITEM = 'TABS_SELECT_ITEM'
export const TABS_CHANGE_ITEM_POSITION = 'TABS_CHANGE_ITEM_POSITION'

// TODO: Think more.
export const EDITOR_SAVE_DATA = 'EDITOR_SAVE_DATA'
